# Travis CI

branches: [develop-travis]
language: c
compiler: gcc

jobs:
  include:
    - os: linux
      script: python examples/buildall.py
    - os: osx
      script: python examples/buildall.py --with-os=macosx
    - os: windows
      before_install:
        - choco install python --version 3.8.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      script: python3 examples/buildall.py --with-os=windows
